
data <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)

data_sub <- subset(data, Date == "1/2/2007" | Date == "2/2/2007")
data_sub$Global_active_power <- as.numeric(data_sub$Global_active_power)
data_sub$Global_reactive_power <- as.numeric(data_sub$Global_reactive_power)
data_sub$Voltage <- as.numeric(data_sub$Voltage)
data_sub$Sub_metering_1 <- as.numeric(data_sub$Sub_metering_1)
data_sub$Sub_metering_2 <- as.numeric(data_sub$Sub_metering_2)
data_sub$Sub_metering_3 <- as.numeric(data_sub$Sub_metering_3)
data_sub$Date <- as.Date(data_sub$Date, "%d/%m/%y")
x <- paste(data_sub$Date, data_sub$Time)
data_sub$DateTime <- as.POSIXct(x, "%d/%m/%y %H:%M:%S")

png('Plot4.png', width=480, height=480)
par(mfrow=c(2,2), mfcol=c(2,2))
plot(data_sub$Global_active_power~data_sub$DateTime, xlab="", ylab="Global Active Power (Kilowatts)", type='line')
plot(data_sub$Sub_metering_1~data_sub$DateTime, xlab="", ylab="Global Active Power (Kilowatts)", type='line')
lines(data_sub$Sub_metering_2~data_sub$DateTime, col='Red')
lines(data_sub$Sub_metering_3~data_sub$DateTime, col='Blue')
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("Black", "Red", "Blue"), lty=1)
plot(data_sub$Voltage~data_sub$DateTime, xlab="", ylab="Voltage (Volt)", type='line')
plot(data_sub$Global_reactive_power~data_sub$DateTime, xlab="", ylab="Global_reactive_power (Kilowatts)", type='line')
dev.off()

